export const KNOWN_EXPORTS: Record<string, Set<string>> = {
  ox_lib: new Set([
    "notify",
    "alertDialog",
    "inputDialog",
    "registerContext",
    "showContext",
    "progressBar",
    "progressCircle",
    "skillCheck",
    "callback",
    "callback.await",
    "addKeybind",
    "locale",
    "print",
    "requestAnimDict",
    "requestModel",
    "requestStreamedTextureDict",
    "requestNamedPtfxAsset",
    "requestScaleformMovie",
    "requestWeaponAsset",
    "raycast",
    "getClosestPlayer",
    "getNearbyPlayers",
    "getClosestVehicle",
    "getNearbyVehicles",
    "getClosestObject",
    "getNearbyObjects",
    "getClosestPed",
    "getNearbyPeds",
    "disableControls",
    "addRadialItem",
    "removeRadialItem",
    "clearRadialItems",
  ]),
  QBCore: new Set([
    "GetCoreObject",
    "Functions.GetPlayer",
    "Functions.GetPlayers",
    "Functions.CreateCallback",
    "Functions.TriggerCallback",
    "Functions.CreateUseableItem",
    "Functions.Notify",
    "Functions.GetPlayerData",
    "Functions.GetIdentifier",
  ]),
  ESX: new Set([
    "GetSharedObject",
    "GetPlayerData",
    "ShowNotification",
    "ShowHelpNotification",
    "TriggerServerCallback",
    "RegisterServerCallback",
    "GetConfig",
  ]),
  qbx_core: new Set([
    "GetCoreObject",
    "GetPlayer",
    "GetPlayers",
    "CreateUseableItem",
    "Notify",
  ]),
};

export const HALLUCINATED_EXPORTS: Record<string, string[]> = {
  ox_lib: [
    "notify_player",
    "NotifyPlayer",
    "showNotification",
    "ShowNotification",
    "displayHelpText",
    "progress",
    "drawText3D",
    "DrawText3D",
  ],
  QBCore: [
    "GiveMoney",
    "giveMoney",
    "NotifyPlayer",
    "notify_player",
    "GetMoney",
    "AddMoney",
    "RemoveMoney",
  ],
  ESX: [
    "GiveMoney",
    "giveMoney",
    "NotifyPlayer",
    "GetMoney",
  ],
};